### ISSUE TITLE
[Etc] ReadMe 문서 작성

### ISSUE THREAD

**Issue by elfinlas** [codestates/WBABEProject-26#13]
### ToDo

- 아래 내역 작성
- [ ] 기술 구현 방법
- [ ] 로직 설명
- [ ] 간단한 구동 동작 방식
- [ ] 기타 서술 내용 작성
